const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  //INCREMENT: Symbol(),
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',

  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',

  //auth : request, success,error
  AUTH_LOGIN: 'AUTH_REQUEST',
  AUTH_CLEAR: 'AUTH_CLEAR',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',

  AUTH_REGISTER: 'AUTH_REGISTER',

  //USER for saga

  // get
  GET_USER_LOGIN: 'GET_USER_LOGIN',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',
  //create
  CREATE_USER_ACTION: 'CREATE_USER_ACTION',
  CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR',
};
export default ACTION_TYPES;
