const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  //INCREMENT: Symbol(),
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',

  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',

  //auth : request, success,error
  AUTH_LOGIN: 'AUTH_REQUEST',
  AUTH_CLEAR: 'AUTH_CLEAR',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',

  AUTH_REGISTER: 'AUTH_REGISTER',
};
export default ACTION_TYPES;
