const ACTION_TYPES = {
  INCREMENT: 'INCREMENT',
  //INCREMENT: Symbol(),
  DECREMENT: 'DECREMENT',
  SET_STEP: 'SET_STEP',

  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
};
export default ACTION_TYPES;
